[server] ##nomal type
mode = "dev"
port = ":8080"

[db] #data access object
[db.user] #이중 map type map[string]map[string]interface{}
host = "mongodb://localhost:27017"
user = "user"
pass = "user!@"
name = "userDB"

[db.account]
host = "mongodb://localhost:27017"
user = "admin"
pass = "admin!@"
name = "accountDB"

#worker pool job object
[[work]] #배열구조, jobs []job
name = "HeartBeat"
desc = "log"
excute = "x"
duration = 300
args = "resv"

[[work]]
name = "exam"
desc = "exam"
excute = "x"
duration = 60
args = "exam"

[log]
level = "debug" # debug or info
fpath = "./logs" # 로그가 생성될 경로 : ./logs, 로그파일명 go-loger_xxx.log
msize = 2000    # 2g : megabytes
mage = 7        # 7days
mbackup = 5    # number of log files


[contract]
netUrl = "https://api.test.wemix.com"
ownerAddress = "0xC86C3c58e0eA6d0e159D883086fB5A9DA102aC09"
contractAddress = "0x20d2434416B2C850Ad7b933E98Deb683cc58e390"

[keyStore]
path = "./keystore/keystore"